"""Author the existing R3 O01 21-card correction population, without executing source."""
from pathlib import Path
import ast, hashlib, json, re
OUT=Path(__file__).parent
MEM=next(p for p in OUT.parents if p.name=='memory-260928-mik-l26')
CODE=MEM.parent/'260928-mik-l26'
TASK=Path('/home/firefox/projects/ar-coordination/tasks/agents-remember/260928_maintained-invariant-knowledge')
REPAIR=TASK/'notes/reports/role-launch/260928-MIK-L26-reviewer-c90c02de-94e9-45be-bd5a-dd61c880a014.memory-r3.evidence/o01-remaining-current-account-repairs.json'
def sha(b):return hashlib.sha256(b).hexdigest()
assert sha(REPAIR.read_bytes())=='296e82ac72113d47ab50d82edf76726f3a7d6250d3bec223241c31dc1c021487'
rows=json.loads(REPAIR.read_text())['rows']
accounts={
'effect.py':('Declares the closed vocabulary of nine planned semantic-history effects.',
'`ADMITTED_EFFECT_LABELS` and `EffectLabel` declare exactly restore, clarify, introduce, strengthen, weaken, replace, split, merge and retire. There is no preserve label. A comparison does not infer an authored effect from the changes it observes.\n\nA label alone supplies no predecessor or successor relationship; planned/history record models own those conditions. The canonical effect, preservation and unresolved-question payloads and their database writers were retired. The former EffectLabelLiteral name and add/narrow/widen/reincarnate vocabulary are not declarations of this module.', []),
'test_knowledge_leaf_read.py':('Pins the converted-tree family-complete leaf selection and its ordinary-read carrier.',
'The source declares twelve unparametrized test functions. A path selects its registered entries, complete directly containing families and their members, while advertising a further family without recursively expanding it. Rows retain applicability, conditions, exclusions, admission, realization roles and typed proofs. Identity seeds retain the separate recorded-family-frontier scope policy. Both read surfaces bind the same selection manifest.\n\nThe assertions cover named registration absence, a route chain without entries, partial indexes, a repository without a commit, bounded seed tails, derived titles, and continuation at the originally named code tree. Fixtures construct converted text documents and Git trees through knowledge_index_test_support. No projection writer or projection64-cap test remains here; the former thirteen-case/projection account is historical removed coverage. This card describes source assertions, not a collection or runtime verdict.', ['test_a_path_selects_one_family_hop_in_the_declared_order','test_both_surfaces_return_one_selection_under_one_manifest','test_a_leaf_walk_resumes_at_its_code_tree_from_the_named_repository','test_identity_seeds_on_a_tree_keep_the_scope_read_beside_the_leaf']),
'diff_scope_test_support.py':('Builds the two-snapshot knowledge and Git fixture used by the diff and review readers.',
'`build_diff_fixture` copies the read-scope fixture into before and candidate datasets, then applies named fixture transitions: successor revisions, realization removals/additions, an unrelated revision and the corresponding source-tree changes. The selected source trees and logical dataset identities remain independently observable.\n\nFixture rows are inserted by RowStore and realization constructors imported from knowledge_rows_test_support. Realization row digests come from knowledge_row_codec_test_support.claim_row_digest, not a production encoder in records.py. Production read/comparison owners consume those index-shaped datasets. The helper provides no canonical writer, lock, label/lineage/duplicate admission guarantee or claim_no_rewrite enforcement. Historical write-shaped helper names describe fixture construction only.', ['build_diff_fixture','_author_revised_revision']),
'read_scope_test_support.py':('Constructs an index-shaped dataset and a real Git tree with the topology needed by bounded scope-read tests.',
'The fixture retains exact invariant/family/revision identities, source locators, applicability, conditions, exclusions and memberships. Its topology deliberately distinguishes directly containing families, sibling realizations, an advertised unreached family, absent/unparsed/mismatched sources and explicit stopping boundaries. Callers use the returned identities rather than inferring relationships from names.\n\nRowStore, revision, family, membership and realization constructors are imported from knowledge_rows_test_support and insert test-only rows. Their production-shaped names do not make them shipped authoring operations or establish the retired storage admission rules. The Git source and current read owners are real; dataset construction is a test fixture.', ['build_read_scope_fixture','_create_invariant','_create_revision','_create_realization']),
'test_knowledge_diff_attribution.py':('Pins changed-path attribution accounting and the limits of what an inspected mapping can establish.',
'The comparison partitions the measured changed-path population into disjoint attributed, confirmed-unregistered and unknown-attribution buckets. Unchanged mapped paths contribute no changed count, repeated claims contribute one path, and selected-subject links are distinguished from completely established outside-selection links. Family scope comes from exact membership revisions.\n\nUnresolved or stale locators do not establish attribution. An unread snapshot prevents a negative conclusion and qualifies outside-selection membership; a known-empty inspected side can support absence. An unavailable observation carries null totals, while a partial denominator names omitted uncarriable paths.\n\nThe two-tree fixture and extra realization rows use test-only knowledge_rows_test_support constructors. `_author_candidate_claim` is a fixture helper despite its historical write-plane docstring. Surviving production anchor readers, source measurement and partition/comparison code supply the asserted output; this suite does not prove canonical write admission.', ['test_the_measured_changes_are_partitioned_once_and_the_buckets_are_disjoint_and_exhaustive','test_a_registered_mapping_that_did_not_resolve_does_not_establish_attribution','test_one_uninspected_snapshot_turns_every_unmapped_change_into_undetermined_attribution','test_an_unavailable_partition_states_no_total_and_never_a_measured_zero']),
'test_knowledge_diff_boundaries.py':('Pins the bounded comparison response, independent record/source changes and honest unavailable observations.',
'The source declares fifteen test functions. They cover requested-tree expansion, visible unattributed gaps, side-specific realization evidence, display paging with whole-union totals, missing or changed snapshot/selector refusals, payload-field comparisons and separation of record changes from source observations. A read page is not reused as the comparison scope.\n\nSerialized response checks exclude strengthening/harmlessness verdicts, mounted UI state, approval and severity. Paired unavailable/available probe substitutions distinguish an unmade observation from a measured gap. Index-shaped fixtures use test-only RowStore/revision helpers; payload substitution isolates the comparison projection and is not evidence of canonical writer duplicate_identity admission.\n\nThe old InventoryFixture/build_inventory_fixture six-case inventory population was removed. No current inventory-walk coverage or production store authoring is attributed to it.', ['test_a_small_display_budget_pages_the_comparison_without_shrinking_its_totals','test_the_record_comparison_reports_exactly_the_payload_field_that_changed','test_a_page_of_a_selection_is_what_the_comparison_displays_not_what_it_selected','test_an_unavailable_observation_is_reported_as_unavailable_and_never_as_a_change_set','test_a_probe_that_measured_the_trees_is_what_makes_a_gap_visible']),
'test_knowledge_index_reuse.py':('Pins reuse of the existing read, view and comparison logic over converted memory-tree indexes.',
'A parity fixture compares selected sets and source-path counts over its test dataset and the index projected from converted text. Views read that index, and a comparison binds two distinct tree indexes. These are read-side parity assertions over a constructed fixture, not production canonical authoring.\n\nThe ordinary converted-tree read returns a complete index and bounded selection; a malformed record names a partial index. An unconverted root instead returns unusable/legacy-format with empty seeds and preserves the retired database bytes. It creates no runtime index there. Legacy selection is refused rather than kept as an alternate readable database route.', ['test_the_reused_selection_selects_the_same_set_over_the_index_as_over_the_database','test_the_ordinary_read_selects_a_converted_memory_tree_through_its_index','test_a_partial_tree_selection_says_it_is_partial','test_an_unconverted_memory_root_refuses_the_retired_database_selection']),
'test_knowledge_paging.py':('Pins token-bounded converted-tree leaf/view paging and continuation bindings.',
'Nine test functions cover exact family walks without duplicate/lost rows, randomized page bounds, an oversized row returned alone and flagged, whole multi-seed block bounds, deferred seed queues, view ordering, code-tree-bound resumed leaf/view walks and refusal of an empty ordering. The named code repository and page-one tree remain part of continuation identity.\n\nFixtures write converted text documents and Git trees through knowledge_index_test_support. Source assertions distinguish page enumeration from full index completeness and refuse invalid or moved continuation inputs without a payload. The retired projection-over-artifact-limit test and former eleven-case account are removed coverage, not a current projection contract.', ['test_a_forty_member_family_pages_from_read_ar_files_through_knowledge_read_exactly_once','test_a_row_larger_than_the_threshold_is_returned_alone_and_flagged','test_the_whole_knowledge_block_of_several_seeds_stays_within_the_threshold','test_a_view_walk_is_bound_to_its_named_code_tree']),
'test_knowledge_read_scope.py':('Pins exact scope stopping, retained-revision grouping, deterministic paging and read-only refusals.',
'Path and exact revision seeds close over the appropriate directly containing families, siblings and recorded locations; an advertised family is reached only by selecting it. Identity seeds group retained revisions separately, while an exact revision excludes its siblings in history. Claim identities, repeated membership edges and distinct source locations are counted separately.\n\nThe ordered page stream keeps one snapshot/manifest across continuation, names truncation and registration/selector absence, and refuses budgets or selection bounds that cannot hold the next result. Refused reads preserve every table and the logical digest; selection remains in the requested namespace.\n\nThe dataset is populated by read_scope_test_support and test-only knowledge_rows_test_support RowStore. Direct fixture inserts and production-shaped constructor names do not enforce the retired production write-admission rules. The current scope selection/page owners are the behavior under test.', ['test_an_exact_family_revision_seed_stops_after_its_own_members','test_an_identity_seed_returns_every_retained_revision_as_its_own_group','test_every_page_declares_the_same_snapshot_and_manifest_and_the_union_equals_the_selection','test_a_refused_read_leaves_every_table_and_the_logical_digest_unchanged']),
'test_knowledge_review_relationship_line.py':('Pins relationship disclosure across a selected subject\'s complete retained successor line.',
'A split or multi-head line displays relationships actually recorded in that line without claiming a unique head or denying displayed evidence. A line recording no relationships states only what was read. Intermediate descendants and memberships moved to an unselected family revision remain visible.\n\nDatasets are copied from the shared fixture and extended with test-only family/revision/membership constructors from knowledge_rows_test_support. Production review readers perform line/head selection and disclosure; those fixture inserts provide no canonical write admission guarantee.', ['test_a_split_line_that_records_relationships_names_them_and_never_denies','test_a_multi_head_line_with_relationships_never_claims_a_unique_head','test_a_relationship_on_an_intermediate_descendant_is_displayed','test_a_membership_moved_onto_an_unselected_family_revision_is_displayed']),
'test_knowledge_review_relationship_reach.py':('Pins relationship evidence at exact member heads, recorded pairings and qualified rename observations.',
'A member\'s moved realization is displayed at its own selected head; ambiguous heads remain unresolved. A withdrawal does not deny a relationship the same payload displays, and retained memberships appear once. Pairing states the recorded relation it uses, never an address resemblance. Rename inference distinguishes measured absence from a measurement not made.\n\nTest-only knowledge_rows_test_support family/revision/membership operations construct the input populations. Real review composition supplies the rendered evidence and refusals; the cases do not reinstate the retired family or membership authoring plane.', ['test_a_member_identities_moved_realization_is_displayed_at_its_own_head','test_a_withdrawal_never_denies_a_relationship_the_same_payload_displays','test_a_pairing_is_qualified_and_an_address_resemblance_never_pairs','test_the_rename_inference_separates_a_measured_absence_from_a_measurement_never_made']),
'test_knowledge_review_revision_selection.py':('Pins revision-head selection without guessed winners, including explicitly damaged fixture graphs.',
'A unique successor chain defaults to the before head and after head, while an intermediate revision remains explicitly selectable. Forks name competing heads and choose no pair. A known-empty after side preserves a removal with its before revision. Heads come from successor edges rather than sorted identity strings, and the review pane renders the selected pair\'s own statements.\n\nFixture construction uses test-only RowStore and revision containers, not a validating production writer. Cycle and dangling-edge cases deliberately alter their scratch dataset to exercise reader refusal; the reason for that SQL is controlled corrupt read input, not proof that a shipped admission layer prevented the graph. Cyclic or missing predecessor evidence remains unresolved and names no guessed pair.', ['test_a_unique_chain_defaults_to_the_first_before_head_versus_the_last_after_head','test_an_intermediate_revision_stays_selectable_history','test_a_successor_cycle_is_unresolved_and_names_no_pair','test_a_dangling_authored_edge_is_unresolved_and_names_the_missing_revision','test_the_review_pane_renders_the_selected_head_pairs_own_statements']),
'test_read_ar_files.py':('Pins source confinement, onboarding deduplication and the ordinary converted-tree knowledge carrier.',
'The source-read cases check exact slices/full text, binary omission, path and symlink confinement, overview/route-chain deduplication, refresh/reset behavior and committed source selection. They remain source assertions; this curation does not call the read_ar_files tool.\n\nPublishedIntentRouteTests constructs a converted memory tree with build_world, resolves its actual PublishedIntentSelection and calls the ordinary route with that context. It asserts source plus a complete derived tree index, named seed/registration refusals and actual carrier field spellings. It no longer substitutes a legacy selection through `_read`.\n\nRemoving the layout marker makes the root unusable/legacy-format with empty seeds. Mounted-route cases build a real coordination declaration and require legacy-format for an unconverted root, with source still returned. Historical direct canonical publication/database-isolation journeys were removed; no current database-selection coverage is claimed.', ['test_the_ordinary_read_returns_source_and_the_selected_tree_index','test_an_unconverted_root_cannot_open_a_legacy_database','test_the_carrier_uses_the_field_spellings_the_payload_actually_returns','test_the_mounted_route_returns_no_knowledge_section_for_unconverted_memory']),
'test_review_assessment_history.py':('Pins the bounded unavailable-curator-channel detail when many retained evidence artifacts are missing.',
'The one remaining regression constructs a missing-evidence channel and monkeypatches review_curator_records._historical_records to raise its exact missing-artifact error. With 100 paths, the source assertions require unavailable, retain every unreadable path and abbreviate the detail; with ten paths whose detail fits PROSE_MAX_LENGTH, they keep the existing wording exactly.\n\nThis is a controlled error-rendering seam in the production channel reader. It does not execute normal assessment capture, cleanup, restart or exact-parent recovery. The former history journey inventory is removed coverage; the module\'s old broad docstring is not evidence that those tests remain.', ['_curator_channel','test_a_leaf_binding_many_missing_curator_artifacts_reads_as_unavailable']),
'test_review_assessment_history_repairs.py':('Pins rejection of invalid retained assessment evidence before canonical curator authority replacement.',
'One parametrized test supplies escaping-alias and corrupt-retained-byte inputs. The fixture prepares a nonempty curator authority and an assessment; one branch points an evidence alias outside the admitted namespace, and the other corrupts a retained evidence file after generation publication but before validation. Both expect CuratorCoherenceError, unchanged canonical bytes and a still-readable current authority.\n\nThe remaining test is this integrity/publication-order boundary. The four former namespace, provenance, channel/custody and snapshot-loss journeys named by the historical module description are no longer current coverage.', ['_nonempty_fixture','_request','test_integrity_rejection_precedes_canonical_authority_replacement']),
'test_review_bounded_pagination.py':('Pins bounded review-record and matrix walks, exact continuation scope and entry-read laziness.',
'Eight test functions cover a complete one-page comparison, long walks without duplication/loss, partitioned item windows, the matrix walk named by the records collection, foreign/snapshot-mismatched records cursors, a moved generation requiring fresh selection, transport page bounds and the entry read\'s refusal to fetch record pages.\n\nThe fixture copies shared index-shaped populations and adds realization rows through test-only knowledge_rows_test_support. Production review/page composition is read back; fixture authoring names are not shipped storage admission. The deleted remainder-test population and former twelve-case coverage account are historical, not assertions supplied by this module.', ['test_every_page_of_a_large_comparison_is_reachable_without_duplicate_or_loss','test_the_records_collection_states_the_matrix_walk_and_the_bound_it_applied','test_a_cursor_from_a_moved_generation_is_refused_with_a_new_generation_action','test_the_entry_read_populates_the_button_without_fetching_record_pages']),
'test_review_family_context.py':('Pins exact family guarantees, memberships and bounded roster continuation in review context.',
'Recorded family revisions supply their own guarantees and memberships; a successor roster is not inherited. Shared members retain canonical revision identity across contexts, and repeated memberships do not inflate the distinct source population. A member change exposes its family context without declaring a guarantee change or an intent verdict.\n\nThe suite distinguishes measured no-family, absent knowledge, no selected subject, one-sided families and ambiguous family lineage. Roster truncation preserves owner counts and its continuation; tokens bind their exact walk, final pages carry only their share, and a multi-page walk terminates without loss. The client route assertions exercise the production adapter.\n\nFamily/revision/membership inputs are inserted by test-only knowledge_rows_test_support. Those fixtures do not enforce the former canonical family authoring plane. Current guarantees and roster meanings are read from exact supplied rows by the surviving production readers.', ['test_a_successor_family_revision_is_read_from_its_own_rows_not_inherited','test_a_shared_member_is_one_canonical_revision_referenced_in_two_contexts','test_missing_knowledge_is_the_reviews_refusal_not_an_empty_family_context','test_the_published_cursor_continues_exactly_the_walk_that_minted_it','test_a_roster_walk_larger_than_one_page_terminates_with_a_page_and_no_failure']),
'test_review_family_member_sources.py':('Pins each family member\'s recorded source locator and the range resolved in its exact selected Git blob.',
'The fixture inserts realization rows through test-only knowledge_rows_test_support and creates real source commits. Production read_family_roster and its side-selected anchor resolver supply the output. Construction through the test namespace is not a production realization write or admission check.\n\nAssertions preserve per-member role/rationale and distinguish symbol/range resolution, whole-file locators, missing or stale locators and ranges beyond the recorded blob. A symbol defined twice carries both defining ranges. Changing a file can preserve an unchanged attributed range on both sides; the existing source fields retain their wire values beside the structured locator fields. No range is inferred by parsing a detail sentence.', ['test_two_members_in_one_file_carry_their_own_locators_ranges_and_rationale','test_a_changed_file_keeps_its_unchanged_attributed_range_on_each_side','test_an_unresolved_locator_is_stated_with_its_recorded_locator_and_no_range','test_a_symbol_defined_twice_carries_every_defining_range','test_the_existing_source_fields_keep_their_published_values']),
'test_review_final_output_receipt.py':('Pins final-output receipts bound to retained code and memory tree comparisons.',
'TreeReceiptFixture creates real temporary code/memory Git repositories, captures their two-tree comparison through the existing owners and passes committed results to receipt attachment/read functions. It calls receipt owners directly; it does not perform the former end-to-end canonical dataset freeze, closeout or integration journeys.\n\nSix current test functions assert both delivered-tree matches and result keys, moved/absent memory or code coverage, unavailable/corrupt comparison handling without blocking an already completed result, forged source binding and leaf scoping, immutable previous receipts labelled by a successor, and readable historical v1 receipts with an explicit lack of memory-tree proof. The former eleven-journey/module-node account is removed coverage. No receipt here supplies semantic acceptance.', ['TreeReceiptFixture','test_receipts_bind_both_delivered_trees_and_keep_both_result_keys','test_memory_movement_and_absent_memory_never_claim_delivered_coverage','test_source_forgery_is_refused_and_receipts_are_leaf_scoped','test_historical_v1_receipt_remains_readable_without_claiming_memory_tree_proof']),
'test_review_intent_summary.py':('Pins changed-intent summary counts and typed answer states over two selected test datasets.',
'The six test functions distinguish added/revised/removed statements and guarantees from realization-only and membership-only changes. A revised member shared by two families counts once on each side. Status-only invariant or version-only family successors count as revisions; a same-guarantee member change remains membership-only. Divergent heads make the summary partial; absent knowledge carries an unavailable refusal and no counts. The route returns typed answers with 200 and an unwired process with 503.\n\n`_shared_base` and `_extend` populate/copy index-shaped datasets through test-only RowStore, family, membership and realization constructors imported from knowledge_rows_test_support. The actual intent_summary_of and route readers are exercised by the assertions; no shipped canonical writer, write lock or admission guarantee is measured by those fixture constructors.', ['test_counts_statement_and_guarantee_heads_and_keeps_other_changes_apart','test_a_record_only_successor_counts_once_on_each_side','test_an_identity_without_one_head_makes_the_summary_partial','test_missing_knowledge_is_unavailable_with_its_refusal_never_zero','test_the_route_answers_every_typed_state_in_the_body']),
'test_review_subject_catalogue.py':('Pins the union, presence, totals, bounded loading and reviewability of a complete subject catalogue.',
'The shared diff fixture is copied and extended for retired, added and bare identities. RowStore and revision constructors come from test-only knowledge_rows_test_support; `_insert_bare_identity` inserts fixture identity rows. It is not a shipped batch insert_invariant_identity operation or proof of production append-only admission.\n\nProduction catalogue/entry/review composition checks kind grouping including before-only identities, one-sided statements, family listing without a statement side, every offered row\'s reviewability and a reason-carrying refusal for an unselectable bare identity. Neighbour reviews remain accessible. Entry totals describe the whole catalogue, an empty catalogue coexists with a measured source inventory, and bounded loading is protected by comparison bindings patched to raise. Browser traversal and relationship/roster paging belong to their separate owners.', ['test_the_catalogue_stays_kind_grouped_when_retired_subjects_exist','test_every_catalogue_row_opens_through_the_normal_review','test_a_recorded_but_unselectable_subject_is_listed_and_its_open_carries_the_reason','test_zero_subjects_is_a_valid_catalogue_beside_the_source_inventory','test_catalogue_loading_runs_no_comparison']),
}
assert len(rows)==len(accounts)==21
plan=[]
for row in rows:
    card=MEM/row['path'];source=row['path'].removeprefix('onboarding/').removesuffix('.md');p=CODE/source
    old=card.read_text();text=p.read_text();tree=ast.parse(text);purpose,logic,symbols=accounts[p.name]
    governing=re.search(r'^## Governing Overview\n.*?(?=^## |\Z)',old,re.M|re.S)
    assert governing, row['path']
    refs=[]
    for name in symbols:
        matches=[n for n in ast.walk(tree) if isinstance(n,(ast.FunctionDef,ast.AsyncFunctionDef,ast.ClassDef)) and n.name==name]
        assert len(matches)==1,(source,name)
        node=matches[0];refs.append(f'| `{name}` supplies the current fixture or assertion described above. | `{name}` | {source}:{node.lineno}-{node.end_lineno} |')
    if not symbols:refs.append(f'| The declared tuple and EffectLabel carry the exact nine-member vocabulary, with no canonical payload or writer. | | {source}:1-{len(text.splitlines())} |')
    test_imports=[n for n in tree.body if isinstance(n,ast.ImportFrom) and n.module=='knowledge_rows_test_support']
    if test_imports:
        n=test_imports[0];refs.append(f'| Fixture construction imports test-only row constructors; it does not call the retired canonical writer. | | {source}:{n.lineno}-{n.end_lineno} |')
        refs.append('| RowStore inserts index-shaped fixture rows without the retired production admission plane. | `RowStore` | mcp/tests/knowledge_rows_test_support.py:247-322 |')
    body=f'# {source}\n\n{governing.group(0).strip()}\n\n## Purpose\n\n{purpose}\n\n## Code Commentary\n\n{logic}\n\n## Evidence\n\n### Docs References\n\nNo Domain Documentation source is configured for this slice.\n\n### Repo-Internal References\n\n| Finding | Anchor | Source |\n| --- | --- | --- |\n'+'\n'.join(refs)+'\n'
    plan.append({'card':row['path'],'source':source,'sourceSha256':sha(p.read_bytes()),'beforeCardSha256':sha(old.encode()),'sealedR3Criterion':row,'authoredPurpose':purpose,'authoredReconciliation':logic,'sourceTestDefinitions':[n.name for n in ast.walk(tree) if isinstance(n,ast.FunctionDef) and n.name.startswith('test_')],'replacement':body})
(OUT/'21-card-authored-plan.json').write_text(json.dumps({'state':'authored-plan-not-applied','originalFinding':'L26-MR1-O01','population':'exact21 distinct R3 residual cards; no new baseline','preserveAcceptedOriginalFindings':13,'sourceSyncFirstSha256':'2a473adf1cbd4589f0408e5e78967b1db6fa848b8443de998c246cddb0231d9c','rows':plan},indent=2)+'\n')
print(json.dumps({'planned':len(plan),'sourceReadOnly':True,'candidateCardsNotYetWritten':True}))
