import itertools,json,pathlib
mem=pathlib.Path('/home/firefox/projects/ar-coordination/worktrees/agents-remember/260928-mik-l26-ar/memory-260928-mik-l26');out=mem/'notes/l26-curation-takeover/d7a5e018/fix3'
old=json.loads((mem/'notes/l26-curation-takeover/d7a5e018/original47-family-examination.json').read_text())
records={json.loads(p.read_text())['id']:json.loads(p.read_text()) for p in (mem/'knowledge/invariants').glob('*.json')}
families={json.loads(p.read_text())['id']:json.loads(p.read_text()) for p in (mem/'knowledge/families').glob('*.json')}
diff={'INV-JM868W','INV-PPGGTW','INV-X23FME'};foundation={'INV-1BBPF3','INV-K69R3M'}
newfamilies=[{'key':'fix3-bounded-diff','kind':'family','fields':{'status':'proposed','title':'Explicit scope and limits of mechanical knowledge diff','guarantee':'For the declared converted knowledge_diff requests, root admission and an absent-selector refusal prevent a falsely empty comparison. The response stays within the shared knowledge-read threshold and states omitted files and patch cuts; within the recorded capture obligation\'s scope, loose-object capture is disclosed. This is a mechanical file comparison, not a semantic verdict or canonical-dataset comparison.','members':sorted(diff),'routes':['mcp/src/agents_remember/application','mcp/src/agents_remember/mcp/tools'],'admission':{'criteria':['joint_guarantee'],'justification':'Root selection, bounded response and disclosed omissions/capture address different ways the same mechanical comparison could appear complete or side-effect-free when it is not. JM868W adds capture disclosure to the overlap with PPGGTW; X23FME supplies scope admission. Their actual scopes remain unchanged; one member does not establish all three parts.'}}},
{'key':'fix3-foundation-inspection','kind':'family','fields':{'status':'proposed','title':'Truthful foundation inspection instructions','guarantee':'For a converted foundation, bootstrap instructions name the supported family, invariant and source_context views and distinguish complete-empty, complete-authored and partial knowledge from admission or legacy refusals. An instruction to inspect knowledge does not establish authoring, publication or repository acceptance.','members':sorted(foundation),'routes':['mcp/src/agents_remember/package_data/skills'],'admission':{'criteria':['joint_guarantee'],'justification':'The examples must lead to supported reads and the state explanation must let the same instructed session interpret what it read. Either alone can misroute or misdescribe the foundation. This is a joint instructional contract, separate from write admission and storage location.'}}}]
# The actual realization locations are read below; route is the authored instructional home, not a grouping premise.
for f in newfamilies:
 if f['key']=='fix3-foundation-inspection':
  f['fields']['routes']=['mcp/src/agents_remember/application','mcp/tests']
  # Skill examples/states are external/task evidence here. These routes hold repository validation of that instructional contract.
no_basis={
'INV-738PC9':'Compared with all other retained obligations: this is read-time exclusion of historical canonical bytes by a Git-tree materializer. The retirement guard/cleanup cluster detects accesses and protects removable companions, but cannot establish this materialization refusal; the bounded-diff and publication clusters do not read this input. No single joint guarantee connecting this refusal to the other retained obligations was supported.',
'INV-J6PAD2':'Compared with all other retained obligations: these negative controls detect regressions across take-back, replacement narrowing and cleanup validation. The publication and retirement families promise distinct product mechanisms; adding this cross-mechanism verification obligation would make a test-control result part of an executable guarantee. The foundation/diff contracts have neither these controls nor these failure conditions. Retain independent verification intent without a family.',
'INV-JZD1F5':'Compared with all other retained obligations, especially YJZKYC: this documentary obligation explains partial-publication/take-back versus post-publication proof failure. YJZKYC explains legacy review knowledge unavailability. Their failure objects and reader decisions differ; generic truthful prose is not a specific shared guarantee. FAM-61DY2V supplies the executable publication contract, not the accuracy of this explanation. Retain this independent documentary obligation.',
'INV-YJZKYC':'Compared with all other retained obligations, especially JZD1F5: legacy review descriptions must state source-only identities and unavailable retired knowledge. Publication-restoration documentation concerns a different transaction/failure window. The historical-review family owns exact operand/custody mechanisms and does not enforce this prose. No supported shared documentary guarantee joins this description to the other retained obligations.'}
rows=[];domains={}
for r in old['rows']:
 x=records[r['invariant']];i=x['id'];rs={'invariant':i,'revision':x['revision'],'status':x['status'],'statement':x['statement'],'applicability':x.get('applicability'),'conditions':x.get('conditions'),'exclusions':x.get('exclusions')}
 if x['status']=='retired':domains[i]='retired';rs['outcome']={'state':'retired-obligation','basis':r['familyOutcome']['basis']}
 elif i in diff:domains[i]='bounded-diff';rs['outcome']={'state':'authored-new-joint-family','familyHandle':'handoff:fix3-bounded-diff','basis':newfamilies[0]['fields']['admission']['justification']}
 elif i in foundation:domains[i]='foundation-instructions';rs['outcome']={'state':'authored-new-joint-family','familyHandle':'handoff:fix3-foundation-inspection','basis':newfamilies[1]['fields']['admission']['justification']}
 elif i in no_basis:domains[i]=i;rs['outcome']={'state':'examined-no-family','basis':no_basis[i]}
 else:
  fs=[f for f in families.values() if f['status']!='retired' and i in f['members']];assert fs,i
  domains[i]=','.join(sorted(f['id'] for f in fs));rs['outcome']={'state':'recorded-membership-preserved','families':[{'id':f['id'],'revision':f['revision'],'guarantee':f['guarantee'],'members':[{'id':m,'revision':records[m]['revision']} for m in f['members']]} for f in fs],'basis':'Compared against the other retained obligations: this supplies the recorded publication or retirement joint guarantee as stated, not a family inferred from a path. Member meaning and exact recorded siblings are unchanged.'}
 rows.append(rs)
retained=[r for r in rows if r['status']!='retired'];pairs=[]
for left,right in itertools.combinations(retained,2):
 l=left['invariant'];r=right['invariant'];same=domains[l]==domains[r]
 if same and domains[l]=='bounded-diff':basis='The same mechanical response can misstate completeness through wrong scope, omitted content or undisclosed capture. The overlap in bounded output does not erase JM868W\'s additional capture clause, PPGGTW\'s complete-response accounting or X23FME\'s root refusal. Each exact member scope is retained in the authored joint guarantee.'
 elif same and domains[l]=='foundation-instructions':basis='Supported inspection examples and correct interpretation of foundation states are jointly necessary for the instructed session to discover existing knowledge without mistaking a refusal or partial foundation for completed authoring.'
 elif same:basis='Both supply distinct parts of the existing '+domains[l]+' guarantee; the current guarantee and full recorded sibling set were read together. No member or family revision change is justified by this comparison.'
 else:basis='Compared the recorded applicability and failure conditions: '+domains[l]+' and '+domains[r]+' govern different operations, observation/verification boundaries or reader decisions. A generic honesty or retirement label would not establish a specific causal joint guarantee between this pair. Existing memberships are preserved; no cross-family edge is authored.'
 pairs.append({'left':{'id':l,'revision':left['revision']},'right':{'id':r,'revision':right['revision']},'judgment':'joint-guarantee' if same else 'no-additional-joint-guarantee','basis':basis})
assert len(rows)==47 and len(retained)==29 and len(pairs)==406
(out/'K05-original47-comparative-examination.json').write_text(json.dumps({'schema':'l26-k05-original47-comparative-examination/v1','rows':rows,'retainedPairComparisons':pairs,'counts':{'original':47,'retired':18,'retained':29,'retainedPairsExamined':406,'existingMembershipOutcomes':20,'newMembershipOutcomes':5,'deliberateNoFamily':4},'sourcesPlane':{'state':'not-recorded','counts':None},'basis':'The original47 population is preserved. Current records and exact sibling revisions were read before authoring. This supplements, rather than rewrites, the earlier examination that omitted comparison among the new obligations.'},indent=2)+'\n')
history=[{'subject':'handoff:'+f['key'],'disposition':'changed','effect':'add','reason':f['fields']['admission']['justification'],'examined':f['fields']['members']} for f in newfamilies]
(out/'K05-family.handoff.json').write_text(json.dumps({'entries':[],'records':newfamilies,'history':history},indent=2)+'\n')
print('47 retained identities;406 retained pair comparisons;2 new family declarations;4 deliberate no-family outcomes')
