import ast, hashlib, json, re
from pathlib import Path
root=Path('/home/firefox/projects/ar-coordination/worktrees/agents-remember/260928-mik-l26-ar')
mem=root/'memory-260928-mik-l26'; code=root/'260928-mik-l26'; out=mem/'notes/l26-curation-takeover/d7a5e018/fix3'
rows=json.loads((root/'task-reports/role-launch/260928-MIK-L26-reviewer-c90c02de-94e9-45be-bd5a-dd61c880a014.memory-r2.evidence/o01-sealed84-coverage.json').read_text())['rows']
# Authored current accounts for the original removed-construct census, not a new population.
accounts={
2:('Admits a taskless foundation request against the settings-declared repository and its resolved external memory root. This is admission of context, not a database or staging-directory writer.', 'The authority carries the settings identity and digest. Admission refuses an enclosure in scope, a different coordination root or code checkout, an unresolved memory context, and a branch/source identity that cannot be read. `bootstrap_scope` names the repository scope; the source revisions are measured Git facts. The former bootstrap staging-directory constant and helper were retired with the canonical database. No staging destination or resume ledger is created here.', ['admit_bootstrap_context','bootstrap_scope','_source_revisions']),
8:('Resolves a canonical review selection into its exact before and candidate source/memory trees, with typed refusals when that selection cannot be resolved.', '`resolve_review_candidate` admits only the declared selectors and enclosure identity. For a live leaf, `_live_resolution` obtains the source tree through the existing capture owner and resolves converted memory through `tree_resolution`. Its baseline_database and candidate_database fields name derived indexes of the selected trees. An unconverted half is explicitly legacy-unavailable, not an empty or substituted dataset. Recorded/closed leaf selection delegates to the retained generation owner. `require_current_candidate_identity` detects a candidate that moved after admission. The old REVIEW_BASELINE_DIRECTORY and REVIEW_CANDIDATE_DIRECTORY layout and dataset receipts are retired.', ['resolve_review_candidate','_live_resolution','require_current_candidate_identity']),
9:('Reopens the exact retained comparison of a committed leaf and reports the limitations of that retained subject.', 'The default generation first uses the converted four-tree reopen and `tree_resolution`. An explicitly named historical generation, or the legacy path, reopens its retained comparison record and passes it to `legacy_comparison_resolution`: exact source and retained evidence remain readable, while canonical dataset halves report legacy unavailability. The reader does not substitute today\'s candidate or recreate a deleted dataset. `ClosedLeafReview` carries the reopened result and its limitation sentence; the removed dataset measurement and provenance helper suite is not part of this module.', ['resolve_committed_leaf_review','ClosedLeafReview','closed_leaf_limitations']),
11:('Composes review evidence from the selected candidate\'s published curator assessments, retained artifacts and measured binding currentness.', 'A resolved candidate reads the immutable curator authority and its artifact references. The returned channels distinguish an assessment collection from the currentness measurement of its exact dependency binding. Canonical detection, verification-observation and evidence-claim collections are retired and explicitly unavailable; they are not measured empty. An unresolved candidate yields unavailable channels. A task-context read without a selected matrix says not-selected for that collection. The removed `_claim_record` projection is not a current reader.', ['review_records_for_resolution','_retired_channel','without_selected_matrix']),
15:('The taskless knowledge-bootstrap CLI admits a named repository and writes a named wave of converted text knowledge through the existing file writer.', '`run` validates the hand-off list, authorization, configured settings and taskless admission before `_run` selects the converted route. A converted root delegates to `run_wave_write`; an unconverted root refuses as legacy-format or by the cutover lock. The parser accepts no database destination, staging root, status or discard mode. Planned/written, writer refusal and invocation refusal remain distinct outcomes. The old canonical bootstrap progress, staged publication and resume/discard command modes are retired.', ['add_arguments','run','_run']),
17:('The converted knowledge CLI\'s file-write routes share admission, owner identity, decision inputs and report rendering.', 'Leaf writes use the supplied enclosure and its leaf owner; named waves use their admitted repository root. Crossing writes retain their separately admitted crossing owner. Each delegates to the file writer rather than selecting a canonical database. `unconverted_write_refusal` supplies the typed legacy/cutover refusal. Database-publication arguments are refused by their CLI front door, not accepted here as an alternative destination. The removed `_file_route_refusal` and legacy dataset writer dispatch are not current routes.', ['run_leaf_write','run_wave_write','run_crossing_write','unconverted_write_refusal']),
18:('Publishes one file through a sibling temporary file and a replacement, with explicit file and directory durability steps.', '`atomic_write_bytes` writes and flushes the sibling temporary file, calls `os.fsync` on its descriptor, then delegates to `atomic_replace`. A failed replacement leaves the previous destination intact and removes the temporary file. After a successful replacement, directory fsync can still fail: the destination has already changed and the source temporary file is gone. This failure window must not be described as rollback. The removed `fsync_file` helper has no current public implementation; file fsync is performed inside the writer.', ['atomic_write_bytes','atomic_replace','_fsync_directory']),
21:('Opens a selected derived knowledge index read-only and checks or creates its one declared schema on an explicitly supplied connection.', '`open_read_only_database` uses APSW read-only flags and a bounded busy timeout. `create_or_validate_schema` creates only the current declared schema when the supplied database is empty, inside an immediate transaction, then sets user_version; otherwise it inspects the existing schema. Inspection checks the declared tables, columns and triggers. Transaction errors roll back and propagate. The retired connection-contract helper and canonical-store WAL/journal selection are absent; this module does not turn an index read into an authoring connection.', ['open_read_only_database','create_or_validate_schema','inspect_schema']),
22:('Publishes bounded evidence files into the durable task report area and independently reads their bytes back.', 'Publication confines a plain filename to the task reports root, writes the supplied content and returns its content identity. Read-back distinguishes matched, missing, mismatched and unreadable evidence. Those states describe the actual retained file, not successful cleanup or a historical observer. The old refused-destination constant and `enclosure_reports_removed` helper were removed; evidence retention is not inferred from their historical names.', ['publish_durable_evidence','read_back_evidence','_require_one_file_name']),
24:('Computes the portable logical identity of a selected derived index using the declared schema and deterministic table contents.', 'The one current schema supplies the table/key order; rows are decoded into the logical body and hashed without physical page layout, file path or retrieval time. `logical_body_from_tables` is the current table-input renderer. `dataset_identity` opens read-only, validates the schema and binds exactly one repository before closing; `bound_repository` refuses no or ambiguous repository rows. The removed `logical_digest_of_tables` and `require_bound_repository` names are not current entry points. These readers provide index identity, not canonical dataset publication.', ['logical_body_from_tables','logical_digest','dataset_identity','bound_repository']),
27:('Declares and fingerprints the single schema used by disposable knowledge indexes.', 'CURRENT_GENERATION composes the retained table declarations into the current version-9 schema. The structure manifest and pinned fingerprint prevent an accidental schema change under the same identity. `generation_for_name` admits only that current schema; `generation_of_database` refuses a different user_version or structure. The former nine-generation runtime registry, per-generation constants, ancestry selector and declared-column helper are retired. Conversion of legacy memory is owned separately, not a read-time schema fallback.', ['structure_manifest','require_pinned_schema_unchanged','generation_for_name','generation_of_database']),
29:('Defines portable snapshot and exact candidate-input identities, and a sealed resolved knowledge context.', '`SnapshotIdentity` is repository_id, schema_version and logical_digest. `ExactCandidateInput` carries the exact tree plus any recorded commit/dirty facts; it does not make a tree an alias for HEAD. `KnowledgeContext` validates its digest and the namespace of the carried snapshot. `context_digest` derives the seal from the other fields. The canonical ChangeBatch, expected-record vocabulary, command union and mutation receipt were removed. A carried opaque reference is a resolved value, not proof that its Git object or task exists.', ['SnapshotIdentity','ExactCandidateInput','KnowledgeContext','context_digest']),
31:('Carries mechanically observed detection signal values with closed conditions, recorded inputs and explicit scope limitations.', '`DetectionSignalPayload` requires the condition vocabulary version, actual input set, observed changes, relationship paths, extractor/policy versions, scope manifest, unmapped paths and limitations. Its validators require the no-semantic-assessment limitation and consistency of truncation, unmapped paths and probe omissions. `detail` must equal the rendering of recorded basis; a trigger-side-only input cannot claim a two-sided comparison or counterpart absence. The canonical DetectionRun request/result/currentness/reproduction record and writer models are retired. A retained signal value is not a stored detection-run channel or a verdict.', ['DetectionSignalPayload','DetectionRecordedInputSet','DetectionScopeManifest','observed_basis_detail']),
32:('Defines a verification-observation value and its recorded artifact, publication and environment references for readers.', '`VerificationObservationPayload` requires an exact code or logical knowledge subject and consistent origin; artifact and publication references carry their own identities, while `RunEnvironment` records the environment supplied by the observer. These models do not verify a runtime merely because it was named. EvidenceClaimPayload and the AddEvidenceClaim/AddVerificationObservation canonical write commands were retired. The observation value\'s survival does not restore a canonical observation collection or writer.', ['VerificationObservationPayload','ResultArtifactReference','PublicationReference','RunEnvironment']),
36:('Carries the exact task-document identity that owns a requirement and the result of resolving that owner.', '`RequirementOwnerRef` names the task-relative path, stable requirement ID and version under their declared patterns. `RequirementOwnerResolution` carries the resolved owner or its refusal. These are frozen values, not filesystem admission or a durable requirement revision. RequirementRevisionPayload and its canonical writer/read graph were retired; ownership resolution cannot silently substitute another requirement version.', ['RequirementOwnerRef','RequirementOwnerResolution']),
49:('Checks the taskless bootstrap command\'s current admission and converted named-wave write boundary.', 'The cases refuse an undeclared repository, refuse an unconverted root without writes, and reject database arguments. A converted-root case drives the named-wave file route. Other cases check memory-init\'s empty/recorded/partial text states and the skill\'s account of those states. The old canonical bootstrap staging, resume, publication and retry scenarios were removed. These are test definitions and assertions; no execution or broader environment qualification is claimed by this card.', ['test_a_repository_the_settings_do_not_declare_is_refused_by_name','test_an_unconverted_memory_root_is_refused_as_legacy_format_and_nothing_is_written','test_a_converted_memory_root_is_written_as_the_named_wave']),
50:('Checks the converted-memory cutover lock across the admitted write/closeout/sync routes and the refusal of canonical database reads.', 'The probes distinguish a definite repository absence from an unreadable or ambiguous Git repository, cover a converted worktree locking an unconverted route, and permit the converting candidate only through its gate. A read case asserts that no read selects a database for a converted tree; another validates hand-off evidence as strings. The old database-writer-freeze test is removed and cannot be cited as a current writer execution. These source assertions are not a current run certificate.', ['test_every_route_refuses_unconverted_memory_once_the_repository_holds_converted_memory','test_no_read_selects_the_database_of_a_converted_tree','test_a_converted_worktree_locks_too_and_an_unanswered_probe_refuses']),
51:('Checks converted knowledge reads, bounded file diffs, index integrity and explicit legacy-format refusals.', 'Current cases read a converted tree through its index; compare knowledge files and adjacent cards; name unknown paths, unheld records, directories and unknown revisions; and report omitted items within the read threshold. Separate cases compare an omitted after revision with the working tree and refuse an unconverted working tree. Retired records are not live selections, partial indexes stay incomplete, and unbuildable indexes return a refusal. The removed combined database-unchanged case is not current coverage; no test execution is asserted here.', ['test_knowledge_diff_serves_the_git_diff_of_the_knowledge_files','test_knowledge_diff_with_no_after_revision_compares_with_the_working_tree','test_knowledge_diff_answers_within_the_read_threshold_and_names_what_it_leaves_out','test_every_knowledge_tool_refuses_legacy_memory_and_opens_no_database']),
52:('Checks append-only leaf attempt histories and the exact-tree memory gate on closeout and recovery.', 'A reopened leaf writes its next attempt without reopening a closed history file; the latest row about a subject governs across attempts. Closeout closes the latest attempt, preview reads its verdict, and an unconverted preview reports no gate verdict. A continued leaf creates its next attempt. A file rewritten while the gate runs must not be committed unjudged, and a missing landed history refuses by name. Removed canonical-dataset reopen scenarios are historical, not current helpers or tests. This card records assertions, not a passing run.', ['test_a_reopened_leaf_writes_its_next_attempt_and_its_history_is_every_file','test_the_public_closeout_refuses_an_open_item_and_commits_once_it_is_answered','test_a_file_rewritten_while_the_gate_runs_is_never_committed_unjudged','test_the_latest_row_about_a_subject_governs_across_attempts']),
55:('Runs the public tool-entry probes declared by the census, using the extracted world and pin owners.', 'EntryPointProbeTests drives the registered entry points through the shared world and declared input pins. The classifier, census controls and phase-budget machinery are extracted owners, not declarations in this module. A probe records the tool\'s actual route outcome; its existence alone proves neither every environment nor every unsupported consumer. Removed local classifier helpers, pin constants and control class names must not be attributed to this file. Test definitions are not an execution result.', ['EntryPointProbeTests']),
56:('Checks supported worktree sync, parked-WIP restoration, real conflicts and continuation/cancellation on fixture repositories.', 'SyncFixture drives the public transaction with an explicit code and memory pair. Cases check paired fast-forward and contract bases, code-conflict continuation, source-ref resolution, cache exclusions, cancelled restoration and memory-content conflict recovery. Memory conflicts are current knowledge-file/content conflicts; the canonical dataset reconciliation engine and its old helper vocabulary are retired. The transaction journal must describe its actual stop/continue state rather than infer completion from matching HEADs. No source or index operation is authorized by reading these tests, and no run is claimed.', ['SyncFixture','WorktreeSyncTests']),
58:('Attributes source paths to the selected subject from the exact resolved before and after knowledge indexes.', '`_read_side` opens the selected derived index and reads its registered mappings; an incomplete or unreadable side remains uninspected. Negative attribution needs complete inspection of both sides, whereas an empty converted index can be fully inspected and confirm absence. Positive attribution records the exact invariant/family/proof relationship that supplied the path. The retired first-generation origin and damaged-half helpers do not establish historical completeness. The source inventory denominator remains separate from a bounded record selection.', ['review_attribution','_read_side','_inspection_state']),
59:('Reopens one immutable comparison generation and reports its current source custody, historical channel availability and retained evidence.', 'Source channels measure whether the exact recorded objects and pins resolve now; recorded release history is a separate fact. `_knowledge_channel` does not open a historical canonical dataset: an explicit deletion is unavailable-history, otherwise the historical dataset is legacy-unavailable. Evidence channels independently read their confined retained references and hashes. No current candidate substitutes for a missing historical object. The former unavailable_channels helper and dataset measurement promise are retired. Snapshot reclamation ordering is owned by review_comparison_reclamation, not inferred from this reader.', ['reopen_comparison_generation','_source_channel','_knowledge_channel','_evidence_channel']),
62:('Plans a converted/unconverted memory crossing from the actual three input trees before the transaction applies it.', '`cross` classifies the three sides by their markers. Three converted sides use structural merge without a conversion; mixed sides use pinned conversion and marker/history ownership before merge and validation. Three unconverted sides do not enter this crossing route. The plan carries files, conflicts and counts; the transaction owner applies and stages it. The removed is_crossing helper is not a current classifier or alternate writer. This module\'s plan is not an acceptance or a grant to mutate a repository.', ['cross','_convert_sides','next_crossing_owner']),
63:('Decodes sealed invariant, family and membership rows from the derived index and computes their read-time content digests.', 'Typed columns, authorship and state-at-origin are decoded under their recorded schema. Revision and membership decoders verify the declared payload seals before returning values. The former row-building, source-anchor and predecessor write helpers were removed. This codec does not insert canonical records or authorize a writer; the index is a projection of admitted text knowledge.', ['decode_revision_row','decode_family_revision_row','decode_member_row','decode_typed_column']),
64:('Provides the read-only StoreViewReader port over a selected index snapshot.', 'The reader projects typed invariant/family/revision/member/realization values and provenance from the supplied connection and snapshot. `open_view_reader` opens that snapshot read-only and returns the handle and reader; the caller owns closing the handle. The former store_view_reader(OpenedKnowledgeStore) bridge is removed. This read port neither selects a substitute canonical store nor admits mutations.', ['StoreViewReader','open_view_reader']),
65:('Finds citation extents and quote candidates without silently choosing an ambiguous source match.', '`FileView` holds source text and extracted definitions; symbol and qualified spans locate declarations, while headings and line-comment blocks provide text extents. `quote_extents_for_path`, `all_quote_matches`, `widened_quotes` and `quote_matches_in` are the current quote APIs; the removed quote_extents/quote_match_extents names are not callable. Normalized/collapsed text retains offset information so a match can map back to source lines. Multiple candidates remain candidates for the citation resolver, not automatic semantic equivalence.', ['FileView','qualified_spans','all_quote_matches','quote_matches_in']),
67:('Declares the closed vocabulary of nine authored semantic-history effects.', 'ADMITTED_EFFECT_LABELS and EffectLabelLiteral name add, replace, narrow, widen, clarify, retire, split, merge and reincarnate. A label alone supplies no effect-specific predecessor or successor relationship. Those conditions belong to the current planned/history record models. The canonical effect payload, writer and cardinality validator were retired; this module carries no preserve label or durable effect operation.', []),
68:('Defines exact final-output receipts for tree-bound comparisons while decoding the historical receipt format separately.', 'FinalOutputReceipt binds the recorded code and knowledge trees and their comparison digest. `tree_match_state` and `tree_output_verdict` compare the actually supplied identities; an unread half is not matching. LegacyFinalOutputReceipt retains the historical code/logical-dataset shape and its validator functions without reopening that dataset. The removed _code_clause/_knowledge_clause helpers are not current rendering owners. A receipt is data about exact compared outputs, never leaf or Git acceptance.', ['FinalOutputReceipt','tree_comparison_digest','tree_output_verdict','LegacyFinalOutputReceipt']),
70:('Measures a stored assessment\'s dependency binding against the exact identities supplied by its current read.', 'Recorded and measured identity maps remain distinct. `measured_binding_status` returns unavailable for unread dependencies, not-measured for absent coverage, stale for an observed disagreement, and current only when the required identities are fully measured and equal. Separate semantic freshness reasons are carried without rewriting the stored assessment. The removed _subject_state helper is not the current measurement owner; absence of evidence cannot be reported as current.', ['measured_binding_status','assessment_currentness','require_assessment_dependencies']),
72:('Defines the strict public worktree response and sync projection vocabulary.', 'SourceLineageProjection reports the applicable code/memory edges and recovery facts. SyncOperationProjection carries the journal\'s actual state, phase, conflicts and next arguments. SyncResolutionProjection describes the side, worktree and files requiring content resolution, with wipRestore distinguishing parked-WIP recovery. Resolution input admits only its declared action. The old SyncKnowledgeConflict and canonical dataset reconciliation fields were retired; these DTOs do not decide conflict content or authorize staging.', ['SourceLineageProjection','SyncOperationProjection','SyncResolutionProjection','SyncResolutionInput']),
73:('Plans and publishes a task reopen transition under the existing repository, contract and recovery admission.', '`_plan_leaf_doc_reset` resolves the canonical leaf document, resets status/lifecycle fields and appends its reopen decision without publishing. `_plan_master_index_reset` updates its exact master row. `_publish_reopen_transition` owns the paired publication and recovery artifacts; `_restore_reopen_artifacts` restores those on failure. The old series-document and review-state helper names are retired, not permissions to reset an active review. A reader of this card may not edit task state or invoke reopen outside its admitted workflow.', ['_plan_leaf_doc_reset','_plan_master_index_reset','_publish_reopen_transition','_restore_reopen_artifacts']),
77:('Checks exact-pair attributed source expansion through converted index relationships.', 'An unchanged path linked by the selected subject opens as context without enlarging the changed-source inventory; a link only in another comparison is refused. The retained pair keeps its exact bytes after live movement. Other cases reject padded paths, preserve undetermined attribution for unread indexes, and include typed proof anchors. The old canonical initialization/freeze helpers are gone; unconverted knowledge reports unavailability. Source assertions are not a current runtime certificate.', ['test_an_unchanged_path_a_recorded_realization_links_opens_as_context_without_counting','test_after_the_live_tree_moves_the_listed_pair_keeps_its_exact_attributed_bytes','test_an_unreadable_snapshot_leaves_the_link_undetermined_rather_than_absent','test_a_tree_index_links_a_path_its_proof_entry_is_anchored_at']),
78:('Checks that attribution precedence never turns an unread knowledge half into a negative conclusion.', 'A readable side can positively attribute its linked path while the remaining population stays unknown. Empty converted knowledge is completely inspected and can confirm absence; a damaged or unreadable half cannot. The fixture uses exact tree indexes, not a fabricated first canonical generation or repaired origin record. These assertions delimit the read\'s knowledge state and make no run claim.', ['test_one_unreadable_knowledge_half_leaves_the_readable_side_attributed_and_the_rest_unknown','test_an_empty_converted_base_counts_as_completely_inspected_for_absence','test_a_damaged_knowledge_half_cannot_support_a_negative_attribution_conclusion']),
79:('Checks reopening historical comparison source records without reading their retired canonical datasets.', 'The fixture assembles a legacy manifest with exact source identities. One case preserves those source objects and patches dataset access to ensure it is never used; another refuses a tampered historical source record rather than retargeting it. The former live freeze/restart/custody scenario suite is removed. These two retained cases are source assertions, not a newly frozen generation or proof of current retention.', ['test_a_legacy_record_preserves_exact_source_and_never_reads_its_dataset','test_a_tampered_historical_source_record_is_refused_instead_of_retargeted']),
80:('Checks review evidence-channel states and currentness measurement of published immutable curator assessments.', 'The converted fixture publishes assessments through their own authority. Cases distinguish unpublished from corrupt/unreadable authority, not-selected matrix collection, measured binding/currentness axes and stale candidates. Retained immutable generations survive damage to the live authority; an unresolvable candidate leaves collections unavailable. Channel counts are refused when their owner did not measure them. Canonical detection, evidence-claim and verification-observation producers and their former tests are removed; no empty-count replacement or executed run is claimed.', ['test_the_composition_measures_the_bindings_it_reads','test_a_retained_curator_generation_survives_a_damaged_live_authority','test_the_channel_model_refuses_a_count_no_owner_measured','test_an_unresolvable_candidate_reports_every_collection_unavailable']),
81:('Checks authored relationship movement and family-declared route sets across exact comparison sides.', 'Synthetic index rows exercise lineage, retractions/additions and authored split/merge edges; a Git rename is labeled inference and does not manufacture an authored edge. A converted-text fixture reads a family\'s declared routes, one relationship per declared route, while an unread side is never called ungoverned. Removed scalar canonical governing-route writers and helpers are not current fixture owners. Bounded selection omissions are not deletions. These assertions record test intent, not an execution result.', ['test_a_moved_realization_displays_both_recorded_paths_under_one_invariant_identity','test_the_same_rename_with_no_authored_edge_is_a_retraction_and_an_addition','test_a_familys_declared_route_set_is_the_governing_association_read_from_text','test_each_declared_route_is_one_relationship_and_an_unread_side_is_never_ungoverned']),
82:('Checks canonical task-context review resolution and typed entry-route results using the current converted fixture.', 'The route cannot accept a browser-chosen candidate path. Missing or unreadable before/candidate halves refuse by name without a substitute; the entry returns the typed refusal instead of raising. Only the two declared selectors are transported, previous binding identity reaches the port, and an absent adapter or unresolvable assessment candidate is explicit. Removed local entry-master/config helpers are not fixture ownership. Test names retaining historical dataset wording do not restore canonical dataset writes, and no run is claimed.', ['test_the_candidate_is_resolved_from_task_context_and_never_from_a_browser_chosen_path','test_the_entry_route_refuses_a_damaged_before_half_instead_of_raising','test_the_transport_admits_exactly_the_two_reviewable_selector_kinds','test_the_previous_binding_identity_reaches_the_port_and_is_compared_against_the_read']),
83:('Checks selected-subject isolation of published curator assessments, their retained bindings and the independently complete source inventory.', 'The journey classifies own assessments as direct, sibling assessments as context, unrelated ones as counted but not displayed, and malformed/unresolved bindings as unresolved. A previous immutable generation is historical rather than current. Page size does not change classification, direct labels must cite a retained list containing the record, and every supplied collection reports its own complete population. The fixture publishes through `_publish_assessments`; canonical detection/evidence-claim/observation/effect producers and their old helpers were removed. A source inventory denominator is independent of record selection. This card claims test assertions, not a thirteen-case or runtime PASS.', ['test_a_sibling_subjects_assessment_is_context_and_never_the_selected_subjects','test_every_page_size_classifies_the_same_records_the_same_way','test_the_source_inventory_is_independent_of_the_record_selection','_publish_assessments']),
}
# Narrow corrections retain the rest of the existing, valid contract.
replacements={
35:[('`ANCHOR_RESOLUTIONS`','the `AnchorResolutionState` literal')],
40:[('`bind_expected_output_tree`','the exact expected tree carried by `begin_git_mutation`')],
41:[('`crossing_applies`','`merge_structure`')],
43:[('`_restore_ignore_file`','`_restore_preparations`')],
60:[('`no_rename_inference`','`_inference_for`')],
69:[('`parse_planned_subject`','`PLANNED_SUBJECT_PATTERN`')],
}
plan=[]
for r in rows:
 src=code/r['sourcePath']; card=mem/r['card']; old=card.read_text(); new=old;mode='preserved-reviewed-current-account';basis=r['reviewerDisposition']
 if r['ordinal'] in accounts:
  purpose,logic,symbols=accounts[r['ordinal']]; mode='current-contract-reconciliation';basis=logic
  m=re.search(r'^## Governing Overview\n.*?(?=^## |\Z)',old,re.M|re.S)
  governing=m.group(0).strip() if m else '## Governing Overview\n\n[Nearest governing overview](overview.md)'
  tree=ast.parse(src.read_text());definitions={n.name:n for n in tree.body if isinstance(n,(ast.FunctionDef,ast.ClassDef))}
  cites=[]
  for sym in symbols:
   assert sym in definitions,(r['ordinal'],sym)
   n=definitions[sym];cites.append(f'| `{sym}` owns the current boundary described above. | `{sym}` | {r["sourcePath"]}:{n.lineno}-{n.end_lineno} |')
  if not symbols:cites=[f'| The effect vocabulary is declared without a payload or writer. | | {r["sourcePath"]}:1-{len(src.read_text().splitlines())} |']
  new=f'# {r["sourcePath"]}\n\n{governing}\n\n## Purpose\n\n{purpose}\n\n## Code Commentary\n\n{logic}\n\n## Evidence\n\n### Repo-Internal References\n\n| Finding | Anchor | Source |\n| --- | --- | --- |\n'+ '\n'.join(cites)+'\n'
 elif r['ordinal'] in replacements:
  mode='named-owner-correction';basis='The retained contract is unchanged; the removed construct name is replaced by its actual current owner.'
  for a,b in replacements[r['ordinal']]:
   if a not in new: print('NO EXACT SPELLING',r['ordinal'],a)
   new=new.replace(a,b)
 plan.append({'ordinal':r['ordinal'],'sourcePath':r['sourcePath'],'card':r['card'],'beforeCardSHA256':hashlib.sha256(old.encode()).hexdigest(),'sourceSHA256':hashlib.sha256(src.read_bytes()).hexdigest(),'action':mode,'basis':basis,'replacement':new if new!=old else None})
(out/'O01-sealed84-authored-plan.json').write_text(json.dumps({'schema':'l26-o01-sealed84-authoring-plan/v1','codeCandidateTree':'bf045a987679cc023f8fdfb8849d28cfcca1adb9','rows':plan},indent=2)+'\n')
print('84 rows; planned changed',sum(x['replacement'] is not None for x in plan),'full accounts',len(accounts))
